
server:
  port: 8084
  
spring:
 application:
  name: muhafiz-service


hillheroes:
 app:
  jwtSecret: hillheroessec@sungur
  jwtExpirationMs: 8640000


 config:
  import: optional:configserver:http://localhost:8090
