server:
 port: 8080
 error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
 #servlet:
    #context-path:/car-rental/api
    #"http://localhost:8080/car-rental/api" Base path bu oluyor.
    
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/carrental_db
  username: carrentaluser
  password: admin
  driver-class-name: org.postgresql.Driver
  
 jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  properties:
    format-sql: true
    #hibernate:
     #enable_lazy_load_no_trans: true
     #antipatern iliskiler arastir
     #Json
     
#defaultta bu ozellik true geliyor.Iliski lazy yapilsa bile view render edilene kadar veya Json datasi olusana kadar 
#Transaction acik kaliyor.
#  open-in-view: false
  
#spring.jpa.open-in-view is enabled by default
#Open in view Hibernate de default olarak acik geliyor
#Bu da many to many iliskilerde lazy yapsaniz bile iliskili objelerin tamamini cekiyor
#controllera kadar getiriyor view de gostermiyor yalnizca. Bu da security acigi olusturuyor.
#Iliskiyi lazy yaptiysak lazy olsun

 servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

hillrent:
  app:
   jwtSecret: hillrent@12    
   jwtExpirationMs: 86400000
   
   
logging:
 file:
  name: logs/hillrent.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    
 level:
  '[org.springframework.web]': INFO
  '[org.hibernate]': INFO
  '[com.hillrent]': DEBUG
    
info:
  application:
   name: 'HillRent Backend App'
   description: 'This is HillRent Backend app dev by HillRent Dev Team'
   version: '@project.version@' 
   #project versionu pom.xmlden alcak ust satirdaki komutla.(pom.xml'de 14.satirda)
    
    
    
  