spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DBNAME}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
hillrent:
  app:
    jwtSecret: ${SECRETKEY}
    jwtExpirationMs: ${EXPIRATIONTIME}

  

  
logging:
 file:
  name: hillrent_prod.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    
 level:
  '[org.springframework.web]': INFO
  '[org.hibernate]': INFO
  '[com.hillrent]': INFO
    
    


management:
  endpoints:
   web:
    exposure:
     include: ['info','health']
    
    
  info:
   env:
    enabled: true
    